#! /bin/bash
set -euf -o pipefail

D="$(dirname "$0")"
: ${LINUX_GIT:="$HOME/g/linux"}

fh () {
	echo fh $1 $2 1>&2
	( cd "$1" && git log --oneline "$2" )
}

show () {
	printf '>'
	for x in "$@"; do
		printf " '%s'" "$(printf "%s" $x | sed "s/'/\\\\'/")"
	done
	echo
}

files=( include/linux/rbtree.h include/linux/rbtree_augmented.h \
	lib/rbtree.c Documentation/rbtree.txt )

for i in "${files[@]}"; do
	mkdir -p "$(dirname "$D/$i")"
	cp $LINUX_GIT/$i "$D/$i"
	fh "$LINUX_GIT" "$i" > "$D/$i.version"
done

sed \
	-e 's|#include <linux/stddef\.h>|#include <stddef.h>|' \
	-i include/linux/rbtree.h

sed \
	-e 's|\#include <linux/stddef\.h>|#include <stddef.h>|' \
	-e '/^#include <linux\/export\.h>$/d' \
	-e '/^EXPORT_SYMBOL(.*);$/d' \
	-e '/include/ a#include <stdbool.h>' \
	-i lib/rbtree.c

#sed -i '/^#include <linux.*>$/d' rbtree.c
