#! /bin/bash

LINUX_GIT=$HOME/g/linux

fh () {
	echo fh $1 $2 1>&2
	( cd "$1" && git show --pretty=format:%H "$2" | head -n1 )
}

files=( include/linux/rbtree.h include/linux/rbtree_augmented.h \
	lib/rbtree.c Documentation/rbtree.txt )

for i in "${files[@]}"; do
	cp $LINUX_GIT/$i .
	fh "$LINUX_GIT" "$i" > $(basename $i).version
done

sed -i '/^EXPORT_SYMBOL(.*);$/d' rbtree.c
sed -i 's|#include <linux/rbtree_augmented.h>|#include <rbtree/rbtree_augmented.h>\
#include <stdbool.h>\
#include <rbtree/compiler.h>|' rbtree.c
sed -i '/#include <linux.*>/d' rbtree.c


sed -i 's|#include <linux/kernel\.h>|#include <ccan/container_of/container_of.h>|' rbtree.h
sed -i 's|#include <linux/stddef\.h>|#include <stddef.h>|' rbtree.h

sed -i 's|#include <linux/compiler\.h>|#include <rbtree/compiler.h>|' rbtree_augmented.h
sed -i 's|#include <linux/rbtree\.h>|#include <rbtree/rbtree.h>|' rbtree_augmented.h

#sed -i '/^#include <linux.*>$/d' rbtree.c
