#! /bin/bash

LINUX_GIT=$HOME/g/linux

fh () {
	( cd "$1" && git show --pretty=format:%H "$2" | head )
}

files=( include/linux/rbtree.h include/linux/rbtree_augmented.h \
	lib/rbtree.c Documentation/rbtree.txt )

for i in "${files[@]}"; do
	cp $LINUX_GIT/$i .
	fh "$LINUX_GIT" "$i" > $(basename $i).version
done

sed -i 's|^EXPORT_SYMBOL(.*);$||' rbtree.c
sed -i 's|^#include <linux.*>$||' rbtree.c
